#!/bin/bash
## Convert HTML files into .harvest files

# (4.1) Creating havests
cd /var/data/ && mkdir harvest

getopts ":a:" opt; do
  case $opt in
    p)
      echo "path: $OPTARG" >&2
      ;;
    u)
      echo "URL: $OPTARG" >&2
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac


#cd /var/data/ && find feed/ -name *.html | xargs -n 10 docs2harvest -o harvest
# (4.2) Indexing
cd /var/data/ && mkdir index && mws/bin/mws-index -I harvest -o index/
# (4.3) Generating elasticsearch json index, will out to `havest/` a .json file for every .harvest file
cd /var/data/ && harvests2json -H harvest/ -I index/
